/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

import controleur.CtrlAbstrait;
import controleur.CtrlVisite;
import controleur.CtrlVisiteur;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;

/**
 *
 * @author btssio
 */
public class VueVisite  extends VueAbstraite {

    public VueVisite(CtrlAbstrait ctrl) {
        super(ctrl);
        initComponents();
        this.setLocation(500, 200);
        this.setBounds(500, 200, 1236, 490);
    }

    public JComboBox getjComboBoxPraticien() {
        return jComboBoxPraticien;
    }

    public void setjComboBoxPraticien(JComboBox jComboBoxPraticien) {
        this.jComboBoxPraticien = jComboBoxPraticien;
    }

    /**
     * Creates new form VueVisite
     */
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        visiteurLabel = new javax.swing.JLabel();
        background = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextNum = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldDate = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxPraticien = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldMotif = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButtonNext = new javax.swing.JButton();
        jButtonPrevious = new javax.swing.JButton();
        jButtonFermer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(654, 450));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        visiteurLabel.setText("Rapport de Visite");
        getContentPane().add(visiteurLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, 190, 60));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vue/background.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 320, 210));

        jLabel1.setText("Numéro de Rapport :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, -1, 30));

        jTextNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNumActionPerformed(evt);
            }
        });
        getContentPane().add(jTextNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 80, 120, -1));

        jLabel2.setText("Date du Rapport :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, 140, 30));

        jTextFieldDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDateActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 170, 120, -1));

        jLabel3.setText("Praticiens :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, 150, 30));

        jComboBoxPraticien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPraticienActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxPraticien, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 120, 140, -1));

        jLabel4.setText("Motif Visite :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 220, 120, -1));
        getContentPane().add(jTextFieldMotif, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 210, 120, -1));

        jLabel5.setText("Bilan :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 260, 90, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 250, 280, 140));

        jButtonNext.setText("Suivant");
        getContentPane().add(jButtonNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 410, -1, -1));

        jButtonPrevious.setText("Précédent");
        getContentPane().add(jButtonPrevious, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 410, -1, -1));

        jButtonFermer.setText("Fermer");
        jButtonFermer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFermerActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonFermer, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 410, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNumActionPerformed

    private void jTextFieldDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDateActionPerformed

    private void jComboBoxPraticienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPraticienActionPerformed
       ((CtrlVisite)controleur).praticienSelectionner();
    }//GEN-LAST:event_jComboBoxPraticienActionPerformed

    private void jButtonFermerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFermerActionPerformed
        try {
            ((CtrlVisite)controleur).visiteQuitter();
        } catch (Exception ex) {
            Logger.getLogger(VueVisiteur.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonFermerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton jButtonFermer;
    private javax.swing.JButton jButtonNext;
    private javax.swing.JButton jButtonPrevious;
    public javax.swing.JComboBox jComboBoxPraticien;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextFieldDate;
    private javax.swing.JTextField jTextFieldMotif;
    private javax.swing.JTextField jTextNum;
    private javax.swing.JLabel visiteurLabel;
    // End of variables declaration//GEN-END:variables
}
